### ISSUE TITLE
Update the documentation according to the new implementation

### ISSUE THREAD

**Issue by tstaubitz** [openHPI/mooc-standards#2]
Several adjustments have been applied to the format since mid 2020.
These still need to be reflected here in the documentation.

**Comment by MrSerth** [comment]
I propose to archive this repository once we published our latest schema to the new [MOOChub Organization](https://github.com/moochub)

**Comment by MrSerth** [comment]
I am closing this issue as the [new schema is now available](https://github.com/moochub/schema)
